# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CX5u4gmBrNWVs82gvzTnmlptwrSfxO77YzszugCZm8EqeF5VpofkPyRbkv96c2hMZ7ZTrifbYnrBJ6kMXC+TBmscq859XxVOwzmjZ00V94Vgrh0QV6ZeyJD48Ku2XQHSbLSlcSF8GYTeu5woQo3cIFHnBaIhoKyS0FsnWuigNokB4yFluyMXqpuVvbmHlEXXqmkMe8oOpC0AbJvI/C5ZkM+BfMw5bOloPESB0ks5f1NOrhybj5u0yULjaVppnjoNrO+l5GjEq2uynQHPEfp5ZpYFBrMUvxnKW9oLPHqpDzUsEtYOFteXSFQATJNYEL+cYAuVUsAHF7X5T/SAl5Ysj+pLzs4kECbf6f98JmMBBaC4mclbmXCw3ZxWmY2DLUsrlF+LVWYAlK3vjanoT28Xdpikb2QeocX75zVIgVCpCHx3eHkn10xf05YG5urkilPr6StXx2GV7oZW/nirrbDPZVEhh6Hsb5R0OnIGDgPncqiTQC5XPr+XLcpMTb9GqinH5z4mXLKnjYeim3sDzAJPujTylJKZH6rsrPOaWXgXu3r0CwhkbGFKOUnGSKfkR+tMPG57gQvk/jHaW+fq9Y5GyFSkhmjB0RD4v9fYKJd4jgOKHYo6nIQ42BkxG1EPfz5hresJZqDYEbaFMAUI0hkij9EFaAaOEbrLomiFynBE6F0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
