travis:
  secure:
    BINSTAR_TOKEN: CX5u4gmBrNWVs82gvzTnmlptwrSfxO77YzszugCZm8EqeF5VpofkPyRbkv96c2hMZ7ZTrifbYnrBJ6kMXC+TBmscq859XxVOwzmjZ00V94Vgrh0QV6ZeyJD48Ku2XQHSbLSlcSF8GYTeu5woQo3cIFHnBaIhoKyS0FsnWuigNokB4yFluyMXqpuVvbmHlEXXqmkMe8oOpC0AbJvI/C5ZkM+BfMw5bOloPESB0ks5f1NOrhybj5u0yULjaVppnjoNrO+l5GjEq2uynQHPEfp5ZpYFBrMUvxnKW9oLPHqpDzUsEtYOFteXSFQATJNYEL+cYAuVUsAHF7X5T/SAl5Ysj+pLzs4kECbf6f98JmMBBaC4mclbmXCw3ZxWmY2DLUsrlF+LVWYAlK3vjanoT28Xdpikb2QeocX75zVIgVCpCHx3eHkn10xf05YG5urkilPr6StXx2GV7oZW/nirrbDPZVEhh6Hsb5R0OnIGDgPncqiTQC5XPr+XLcpMTb9GqinH5z4mXLKnjYeim3sDzAJPujTylJKZH6rsrPOaWXgXu3r0CwhkbGFKOUnGSKfkR+tMPG57gQvk/jHaW+fq9Y5GyFSkhmjB0RD4v9fYKJd4jgOKHYo6nIQ42BkxG1EPfz5hresJZqDYEbaFMAUI0hkij9EFaAaOEbrLomiFynBE6F0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
