travis:
  secure:
    BINSTAR_TOKEN: mJbBjyHGG87GiN187qZaU+MPFy7n89H0XXgEMkQoX2nY6zqtIJRLxeC4NW3ueeKS6oAIBb2qNL982mjJ0kSQqLYbe+BljFxF05Ze0uiy5yyAHS5uwUMDcoNBdCIQxLE359DvZ/9jShbLZ0ZdqMbztq1kdReO3GCIRqta30tU+AnBR6aCxTM5e8sDCtZnDVXJCRm5E8I9VAYkiGYMfR91/h5GQJRi6WRxl3fhhddkoVQGatY6HPKbO+OY5dt/5hxeV63iBsc+1xSiy9IlQgn4h1JxUSRM+pAeFLQ2gWpkYzmjlPUPsDAZnr3ER8B9YZe0VIihePIgGl3FaL/g3IjuKW9Yd5zn7aT04Z6/WSJUA/nEMRYSq0h+Mze3gE91pxPghHthKu57PBkXW7rddIgeqt3cwGK06M09RRqRKGdryHlrnqKjaZ/Z44s0ybh68bkEE+QJF30ewlWu3d6zyUNF5nKGRdVqQPjCLOaOsCF/r3/k9BWkoVIAvtr1RcyiySeZdZhxh2sg/KRycLG1lQDFmBsGus0sL0htOI6ECF1ATsrJeepCBsI+i2WfQxsZ+2oKUb5zaXWgCR6QAIzTM3EYc5CuS3FGHyL3WZ3jzRFbJJtTc2/UQoXRVGCHNfJKEhgsxf5OLF5LqsJJ8X/D3o64pZasOE1xHQuwiPrRKQwNgqo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
